services:
  frontend:
    image: node:20-alpine
    container_name: frontend-dev
    working_dir: /app
    volumes:
      - C:/IMPORTANT/NSU/3/SoftwareDesign/system/library_frontend/Frontend:/app
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    command: sh -c "npm ci || npm install && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - library